import { parseYaml } from 'obsidian'
import type { TaskComment } from '../types'

export const FRONTMATTER_KEY = 'pm-project'
export const TASK_FRONTMATTER_KEY = 'pm-task'

// ─── Parse ──────────────────────────────────────────────────────────────────

export function parseFrontmatter(content: string): {
  frontmatter: Record<string, unknown> | null
  body: string
} {
  if (!content.startsWith('---')) return { frontmatter: null, body: content }
  const end = content.indexOf('\n---', 4)
  if (end === -1) return { frontmatter: null, body: content }
  const raw = content.slice(4, end)
  const body = content.slice(end + 4).trim()
  try {
    return { frontmatter: parseYaml(raw) as Record<string, unknown>, body }
  } catch {
    return { frontmatter: null, body: content }
  }
}

/**
 * Heading of the managed comments section. The trailing HTML comment is a
 * machine marker, not decoration: it lets the parser find *our* section without
 * guessing, so a user who writes their own "## Comments" heading in a
 * description keeps it. Obsidian hides HTML comments when rendering.
 */
export const COMMENTS_HEADING = '## Comments <!-- pm:comments -->'

const COMMENTS_SECTION = /^## Comments <!-- pm:comments -->[ \t]*$/m

/**
 * The generated `## Subtasks` heading plus the checklist lines directly under
 * it — and nothing else.
 *
 * The bound matters. This used to be `/\n## Subtasks[\s\S]*$/`, which ate
 * everything from the heading to end-of-file, so any note a user typed below
 * the checklist was silently destroyed on the next body rewrite. Only the
 * generated `- [ ] [[link]]` lines belong to us.
 */
const GENERATED_SUBTASKS = /(^|\n)## Subtasks[ \t]*\n(?:[ \t]*-[ \t]*\[[ xX]\][ \t]*\[\[[^\n]*\n?)*(?:[ \t]*\n)*/

const COMMENT_HEADING = /^### (.+?) — (\S+)(?: <!-- run:(.*?) -->)?[ \t]*$/

/**
 * Split a task note body into the user's description and the managed comments.
 *
 * Content the user put below the generated subtask checklist survives, but it
 * moves: the description is re-serialized above the `Project:`/`Parent:` link,
 * so text that was at the bottom of the file comes back at the top of it. That
 * is the price of having exactly one home for free-form text, and it beats the
 * alternative of deleting it.
 */
export function parseTaskBody(body: string): { description: string; comments: TaskComment[] } {
  const match = COMMENTS_SECTION.exec(body)
  const description = match ? body.slice(0, match.index) : body
  const comments = match ? parseComments(body.slice(match.index + match[0].length)) : []
  return { description: stripAutoGeneratedContent(description), comments }
}

/** Strip auto-generated wiki-link lines from task body so they don't get duplicated on save */
export function stripAutoGeneratedContent(body: string): string {
  let result = body
  result = result.replace(/^Project: \[\[.*\]\]$/gm, '')
  result = result.replace(/^Parent: \[\[.*\]\]$/gm, '')
  result = result.replace(GENERATED_SUBTASKS, '$1')
  return result.trim()
}

/** Parse the body of the comments section (everything after its heading). */
function parseComments(section: string): TaskComment[] {
  const comments: TaskComment[] = []
  let current: { author: string; at: string; runId?: string } | null = null
  let buffer: string[] = []

  const flush = (): void => {
    if (!current) return
    const text = buffer.join('\n').trim()
    // A heading with no body is a half-written entry, not a comment.
    if (text) comments.push({ ...current, body: text })
  }

  for (const line of section.split('\n')) {
    const heading = COMMENT_HEADING.exec(line)
    if (heading) {
      flush()
      current = { author: heading[1], at: heading[2], ...(heading[3] ? { runId: heading[3] } : {}) }
      buffer = []
    } else if (current) {
      buffer.push(line)
    }
  }
  flush()
  return comments
}

/** Render comments as the managed section, heading included. Empty list → ''. */
export function serializeComments(comments: TaskComment[] | undefined): string[] {
  if (!comments?.length) return []
  const lines = ['', COMMENTS_HEADING]
  for (const c of comments) {
    lines.push('')
    lines.push(`### ${c.author} — ${c.at}${c.runId ? ` <!-- run:${c.runId} -->` : ''}`)
    lines.push('')
    lines.push(c.body.trim())
  }
  return lines
}

// ─── YAML Writer ────────────────────────────────────────────────────────────

/** Minimal YAML serializer (handles strings, numbers, booleans, arrays, objects) */
export function appendYaml(lines: string[], obj: Record<string, unknown>, indent: number): void {
  const pad = '  '.repeat(indent)
  for (const [key, val] of Object.entries(obj)) {
    if (val === null || val === undefined) {
      lines.push(`${pad}${key}:`)
    } else if (typeof val === 'boolean') {
      lines.push(`${pad}${key}: ${val}`)
    } else if (typeof val === 'number') {
      lines.push(`${pad}${key}: ${val}`)
    } else if (typeof val === 'string') {
      const escaped = val.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
      lines.push(`${pad}${key}: "${escaped}"`)
    } else if (Array.isArray(val)) {
      if (val.length === 0) {
        lines.push(`${pad}${key}: []`)
      } else if (typeof val[0] === 'object') {
        lines.push(`${pad}${key}:`)
        for (const item of val) {
          const entries = Object.entries(item as Record<string, unknown>)
          if (entries.length === 0) continue
          const [firstKey, firstVal] = entries[0]
          lines.push(`${pad}  - ${firstKey}: ${JSON.stringify(firstVal)}`)
          for (const [k, v] of entries.slice(1)) {
            lines.push(`${pad}    ${k}: ${JSON.stringify(v)}`)
          }
        }
      } else {
        const items = val.map((v) => JSON.stringify(v)).join(', ')
        lines.push(`${pad}${key}: [${items}]`)
      }
    } else if (typeof val === 'object') {
      const keys = Object.keys(val)
      if (keys.length === 0) {
        lines.push(`${pad}${key}: {}`)
      } else {
        lines.push(`${pad}${key}:`)
        appendYaml(lines, val as Record<string, unknown>, indent + 1)
      }
    }
  }
}

/** Check if a project file uses the old embedded-tasks format */
export function isOldFormat(frontmatter: Record<string, unknown>): boolean {
  return Array.isArray(frontmatter.tasks) && frontmatter.tasks.length > 0 && !Array.isArray(frontmatter.taskIds)
}
