import { describe, expect, it } from 'vitest'
import {
  appendYaml,
  COMMENTS_HEADING,
  isOldFormat,
  parseFrontmatter,
  parseTaskBody,
  serializeComments,
  stripAutoGeneratedContent
} from './YamlParser'

describe('parseFrontmatter', () => {
  it('returns null frontmatter when the document has no fences', () => {
    const { frontmatter, body } = parseFrontmatter('just body text')
    expect(frontmatter).toBeNull()
    expect(body).toBe('just body text')
  })

  it('parses a fenced frontmatter block', () => {
    const doc = '---\ntitle: "Hello"\ncount: 3\n---\n\n# Body'
    const { frontmatter, body } = parseFrontmatter(doc)
    expect(frontmatter).toEqual({ title: 'Hello', count: 3 })
    expect(body).toBe('# Body')
  })

  it('returns the full content as body when the closing fence is missing', () => {
    const doc = '---\ntitle: "Hello"\n'
    const { frontmatter, body } = parseFrontmatter(doc)
    expect(frontmatter).toBeNull()
    expect(body).toBe(doc)
  })

  it('falls back to null on malformed yaml', () => {
    const doc = '---\n: : :\n---\nbody'
    const { frontmatter } = parseFrontmatter(doc)
    expect(frontmatter).toBeNull()
  })
})

describe('stripAutoGeneratedContent', () => {
  it('removes Project wiki-link lines', () => {
    expect(stripAutoGeneratedContent('Project: [[my-project|My Project]]')).toBe('')
  })

  it('removes Parent wiki-link lines', () => {
    expect(stripAutoGeneratedContent('Parent: [[parent-slug|Parent]]')).toBe('')
  })

  it('removes a trailing Subtasks section', () => {
    const body = 'Description goes here\n\n## Subtasks\n- [ ] [[sub|Sub]]'
    expect(stripAutoGeneratedContent(body)).toBe('Description goes here')
  })

  it('preserves user content when no auto-generated markers exist', () => {
    expect(stripAutoGeneratedContent('Plain description.')).toBe('Plain description.')
  })

  it('keeps user text written below the generated subtask checklist', () => {
    // Regression: the strip used to run to end-of-file, so anything typed under
    // the checklist was destroyed on the next body rewrite.
    const body = 'Description\n\n## Subtasks\n- [ ] [[sub|Sub]]\n- [x] [[two|Two]]\n\nMy notes survive.'
    expect(stripAutoGeneratedContent(body)).toBe('Description\n\nMy notes survive.')
  })

  it('does not eat a user checklist that is not under the Subtasks heading', () => {
    const body = 'Steps:\n- [ ] [[one|One]]\n\n## Subtasks\n- [ ] [[sub|Sub]]'
    expect(stripAutoGeneratedContent(body)).toBe('Steps:\n- [ ] [[one|One]]')
  })
})

describe('parseTaskBody', () => {
  const section = [
    'Description.',
    '',
    'Project: [[proj|Proj]]',
    '',
    '## Subtasks',
    '- [ ] [[sub|Sub]]',
    '',
    COMMENTS_HEADING,
    '',
    '### claude-zixi — 2026-08-19T19:36:06-04:00 <!-- run:run-1 -->',
    '',
    '**Root cause:** the thing.',
    '',
    'More detail.',
    '',
    '### jtalley — 2026-08-19T20:00:00-04:00',
    '',
    'Confirmed.'
  ].join('\n')

  it('splits description from comments', () => {
    const { description, comments } = parseTaskBody(section)
    expect(description).toBe('Description.')
    expect(comments).toHaveLength(2)
  })

  it('parses author, timestamp and run id', () => {
    const [first, second] = parseTaskBody(section).comments
    expect(first).toEqual({
      author: 'claude-zixi',
      at: '2026-08-19T19:36:06-04:00',
      runId: 'run-1',
      body: '**Root cause:** the thing.\n\nMore detail.'
    })
    expect(second.author).toBe('jtalley')
    expect(second.runId).toBeUndefined()
  })

  it('leaves a user-authored "## Comments" heading in the description', () => {
    // Only the marked heading is ours. An unmarked one is the user's prose.
    const { description, comments } = parseTaskBody('Notes\n\n## Comments\n\nmine')
    expect(description).toBe('Notes\n\n## Comments\n\nmine')
    expect(comments).toEqual([])
  })

  it('drops a heading with no body rather than emitting an empty comment', () => {
    expect(parseTaskBody(`x\n\n${COMMENTS_HEADING}\n\n### bot — 2026-01-01T00:00:00Z\n`).comments).toEqual([])
  })

  it('round-trips through serializeComments', () => {
    const { comments } = parseTaskBody(section)
    const rebuilt = `head\n${serializeComments(comments).join('\n')}`
    expect(parseTaskBody(rebuilt).comments).toEqual(comments)
  })
})

describe('isOldFormat', () => {
  it('is true when tasks is a non-empty array and taskIds is absent', () => {
    expect(isOldFormat({ tasks: [{ id: 'a' }] })).toBe(true)
  })

  it('is false when taskIds is present even if tasks is also set', () => {
    expect(isOldFormat({ tasks: [{ id: 'a' }], taskIds: ['a'] })).toBe(false)
  })

  it('is false when tasks is empty', () => {
    expect(isOldFormat({ tasks: [] })).toBe(false)
  })

  it('is false when tasks is absent', () => {
    expect(isOldFormat({ title: 'Project' })).toBe(false)
  })
})

describe('appendYaml', () => {
  it('serializes primitive types with quoted strings and unquoted numbers/bools', () => {
    const lines: string[] = []
    appendYaml(lines, { s: 'hi', n: 2, b: true, nil: null }, 0)
    expect(lines).toEqual(['s: "hi"', 'n: 2', 'b: true', 'nil:'])
  })

  it('escapes quotes, backslashes, and newlines in strings', () => {
    const lines: string[] = []
    appendYaml(lines, { s: 'a "b"\n\\c' }, 0)
    expect(lines).toEqual(['s: "a \\"b\\"\\n\\\\c"'])
  })

  it('emits inline arrays for primitive items and empty arrays as []', () => {
    const lines: string[] = []
    appendYaml(lines, { list: ['a', 'b'], empty: [] }, 0)
    expect(lines).toEqual(['list: ["a", "b"]', 'empty: []'])
  })

  it('emits nested blocks for arrays of objects', () => {
    const lines: string[] = []
    appendYaml(
      lines,
      {
        items: [
          { k: 'v1', n: 1 },
          { k: 'v2', n: 2 }
        ]
      },
      0
    )
    expect(lines).toEqual(['items:', '  - k: "v1"', '    n: 1', '  - k: "v2"', '    n: 2'])
  })

  it('indents nested objects by the given amount', () => {
    const lines: string[] = []
    appendYaml(lines, { outer: { inner: 'x' } }, 0)
    expect(lines).toEqual(['outer:', '  inner: "x"'])
  })
})
